### ISSUE TITLE
Could NOT find AppImageKit? 

### ISSUE THREAD

**Issue by Amppa** [Ultimaker/cura-build#183]
I am trying to build Cura on Ubuntu 18.04 x64
On "cmake .." step, it's stuck on error of AppImageKit, the log is as below

```
CMake Error at CMakeLists.txt:23 (get_filename_component):
  get_filename_component unknown component CACHE

CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find AppImageKit (missing: APPIMAGEKIT_ASSISTANT_EXECUTABLE
  APPIMAGEKIT_APPRUN_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindAppImageKit.cmake:6 (find_package_handle_standard_args)
  packaging/linux.cmake:2 (find_package)
  CMakeLists.txt:85 (include)

```

It strange that FindAppImageKit is ...not a lib? or how to set it up? I can't find any post about this error msg.

Thx

**Comment by thopiekar** [comment]
Take a look at cura-build-environment 😉

**Comment by Amppa** [comment]
Hi @thopiekar ,
I've tried, but I met a different build error before.

When make cure-build-environment at NumPy module, which need setuptools

```
[ 13%] Performing build step for 'NumPy'
Running from numpy source directory.
Traceback (most recent call last):
  File "setup.py", line 394, in <module>
    setup_package()
  File "setup.py", line 371, in setup_package
    from setuptools import setup
ImportError: No module named 'setuptools'
CMakeFiles/NumPy.dir/build.make:113: recipe for target 'NumPy-prefix/src/NumPy-stamp/NumPy-build' failed
make[2]: *** [NumPy-prefix/src/NumPy-stamp/NumPy-build] Error 1
CMakeFiles/Makefile2:607: recipe for target 'CMakeFiles/NumPy.dir/all' failed
```

I find a post which mention about this question,
https://github.com/Ultimaker/Cura/issues/3384
Yiyu guess it's because the "new build python" doesn't build Setuptools, either can't load site-packages from OS's python. His workaround it copy Setuptools from the OS (.local/lib/python3.X/site-packages/setuptools) to (git/cura-build-environment/build/lib/python3.5/site-packages/)

...not work for me...

**Comment by thopiekar** [comment]
As far as I know this append when you miss to install openssl or a one which is "too new" (>=1.1.0). I fixed the problem on my own fork of cura-build-environment by adding the correct openssl version.

However, make sure you install the correct version, then ensurepip should work and thus setuptools should be installed just fine. The core issue, is that the ssl module in your python build is missing and therefore setuptools can't be downloaded from a https location.

Regards

**Comment by Amppa** [comment]
@thopiekar  can you tell how to change openssl version locally?

I've tried to downgrade the whole system openssl by
wget https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/7531893/+files/openssl_1.0.1-4ubuntu5.31_amd64.deb
sudo dpkg -i openssl_1.0.1-4ubuntu5.31_amd64.deb
openssl version

than
(make clean, not necessary)
make

It still gets No setuptools fail
/cura-build-environment/build/Python-prefix/src/Python/Modules/_hashopenssl.c:51:23: error: storage size of ‘CONST_new_md5_ctx’ isn’t known

**Comment by jianqingHuang** [comment]
hi @thopiekar @Amppa 
This error is so consistent with me.

root@ubuntu:~/cura-build/build# cmake ..
CMake Error at CMakeLists.txt:23 (get_filename_component):
  get_filename_component unknown component CACHE


CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find AppImageKit (missing: APPIMAGEKIT_ASSISTANT_EXECUTABLE
  APPIMAGEKIT_APPRUN_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindAppImageKit.cmake:6 (find_package_handle_standard_args)
  packaging/linux.cmake:2 (find_package)
  CMakeLists.txt:85 (include)


-- Configuring incomplete, errors occurred!

**Comment by thopiekar** [comment]
I can point you later to my fork. Only problem is (I think) that AppImageKit inside it is too recent.
Also I miss some new build recipes I think.

However, I will have a look and if needed make an downgrade on AppImageKit in a separate branch. You can then contribute and add all the missing recipes, which have been added since 3.4, if you like.

The only alternative would be using the Docker image Ultimaker is probably using or using an older Linux distribution.

Regards.

**Comment by Amppa** [comment]
BTW @thopiekar can you share the OS environment and python version which is static for developing? Even for make cura-build-environment I met some unexpected problem. Thx

**Comment by cubiq** [comment]
I was able to compile in Ubuntu 18.04 by simply upgrading python to 3.5.6 in the cmake file

**Comment by Ghostkeeper** [comment]
Which CMake file did you adjust? The one that requests Python with a certain minimum version, or the one that installs CPython?

**Comment by cubiq** [comment]
Here https://github.com/Ultimaker/cura-build-environment/blob/master/projects/python.cmake

I believe it has something to do with the updated openssl libraries.

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
